import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {Calendar} from 'lucide-react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-secondary text-secondary-foreground p-4 flex items-center justify-center">
          <Calendar className="mr-2" />
          <h1 className="text-xl font-bold">Planer</h1>
        </header>
        {children}
        <footer className="bg-secondary text-secondary-foreground p-4 text-center">
          Realizado por Mideas Sistemas
        </footer>
      </body>
    </html>
  );
}

